name: linter
on: [commit]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: my-step
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '7.4'
      - name: Install
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint